/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DB_H_RPCGEN
#define _RPC_DB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SensorData {
	int dataId;
	int noValues;
	float *value;
};
typedef struct SensorData SensorData;

#define RPC_DB 1
#define RPC_DB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(struct SensorData *, CLIENT *);
extern  int * add_1_svc(struct SensorData *, struct svc_req *);
#define DELETE 2
extern  int * delete_1(int *, CLIENT *);
extern  int * delete_1_svc(int *, struct svc_req *);
#define UPDATE 3
extern  int * update_1(struct SensorData *, CLIENT *);
extern  int * update_1_svc(struct SensorData *, struct svc_req *);
#define READ 4
extern  int * read_1(int *, CLIENT *);
extern  int * read_1_svc(int *, struct svc_req *);
extern int rpc_db_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define DELETE 2
extern  int * delete_1();
extern  int * delete_1_svc();
#define UPDATE 3
extern  int * update_1();
extern  int * update_1_svc();
#define READ 4
extern  int * read_1();
extern  int * read_1_svc();
extern int rpc_db_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SensorData (XDR *, SensorData*);

#else /* K&R C */
extern bool_t xdr_SensorData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DB_H_RPCGEN */
