/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "group.h"


void
check_prog_1(char *host, char *nume, char *grupa)
{
	CLIENT *clnt;
	char * *result_1;
	struct student  grade_1_arg = {nume, grupa};

#ifndef	DEBUG
	clnt = clnt_create (host, CHECK_PROG, CHECK_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = grade_1(&grade_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Response: %s\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	struct student s;

	if (argc < 4) {
		printf ("usage: %s server_host Nume Grupa\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	check_prog_1 (host, argv[2], argv[3]);
exit (0);
}
