/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMA_H_RPCGEN
#define _SUMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nod {
	int x;
	int y;
};
typedef struct nod nod;

#define SUMA_PROG 1234567
#define SUMA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_SUMA 1
extern  int * get_suma_1(struct nod *, CLIENT *);
extern  int * get_suma_1_svc(struct nod *, struct svc_req *);
extern int suma_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_SUMA 1
extern  int * get_suma_1();
extern  int * get_suma_1_svc();
extern int suma_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nod (XDR *, nod*);

#else /* K&R C */
extern bool_t xdr_nod ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMA_H_RPCGEN */
