/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"


void
suma_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int  *result_1;
	struct nod  get_suma_1_arg = {x, y};

#ifndef	DEBUG
	clnt = clnt_create (host, SUMA_PROG, SUMA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_suma_1(&get_suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Suma de la server: %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int x, y;

	if (argc < 4) {
		printf ("usage: %s server_host x y\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	x = atoi(argv[2]);
	y = atoi(argv[3]);
	suma_prog_1 (host, x, y);
exit (0);
}
