/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_db.h"

bool_t
xdr_SensorData (XDR *xdrs, SensorData *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dataId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->noValues))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->value.value_val, (u_int *) &objp->value.value_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_UserPackage (XDR *xdrs, UserPackage *objp)
{
	register int32_t *buf;

	 if (!xdr_SensorData (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SpecificId (XDR *xdrs, SpecificId *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dataId))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	return TRUE;
}
