/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_db.h"
#include <iostream>
#include <fstream>

#define LENGTH 100
#define USER_EXISTS -1
#define NOT_LOGGED_IN -2
#define ERROR -1
#define OK 0

#define ADDED 1
#define UPDATED 2

int login(char *host, char *name) {
	CLIENT *clnt;
	int *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = login_1(&name, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if (*result_1 == USER_EXISTS) {
			std::cout << "This user is already logged in" << std::endl;
		} else {
			std::cout << "Login success. Here is your cookie key: " << *result_1 << std::endl;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

char *readall(char *host, char *name) {
	CLIENT *clnt;
	char **result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = readall_1(&name, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		std::cout << *result_1;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

char *store(char *host, char *name) {
	CLIENT *clnt;
	char **result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = store_1(&name, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

int *load(char *host, char *name) {
	CLIENT *clnt;
	int *result_1;
	char pl[4] = "plm";
	LoadData data = {name, pl};

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = load_1(&data, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return result_1;
}

void getstatall(char *host, char *name) {
	CLIENT *clnt;
	char **result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getstatall_1(&name, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		std::cout << *result_1;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int logout(char *host, char *name) {
	CLIENT *clnt;
	int *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = logout_1(&name, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if (*result_1 == ERROR) {
			std::cout << "Error while logging out" << std::endl;
		} else {
			std::cout << "Logout success" << std::endl;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;

}

int add(char *host, char *username, struct SensorData entry) {
	
	CLIENT *clnt;
	int *result_1;
	struct UserPackage p = {entry, username};
	//for (int i = 0; i < entry.noValues; i++)
	//	std::cout << p.data.value[i] << std::endl;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&p, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if (*result_1 == ERROR) {
			std::cout << "Error while adding data" << std::endl;
		} else {
			std::cout << "Add was successful" << std::endl;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

void read(char *host, char *username, int dataId) {
	
	CLIENT *clnt;
	char **result_1;
	struct SpecificId p = {dataId, username};
	//for (int i = 0; i < entry.noValues; i++)
	//	std::cout << p.data.value[i] << std::endl;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = read_1(&p, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else if (strcmp(*result_1, "ERROR")) {
			std::cout << "Data read successfully" << std::endl;
			std::cout << *result_1;
	} else {
				std::cout << "Invalid id, the entry doesn't exist\n";
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	//return *result_1;
}

void getstat(char *host, char *username, int dataId) {
	
	CLIENT *clnt;
	char **result_1;
	struct SpecificId p = {dataId, username};
	//for (int i = 0; i < entry.noValues; i++)
	//	std::cout << p.data.value[i] << std::endl;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getstat_1(&p, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else if (strcmp(*result_1, "ERROR")) {
		std::cout << "Stats read successfully" << std::endl;
		std::cout << *result_1;
	} else {
		std::cout << "Invalid id, the entry doesn't exist\n";
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	//return *result_1;
}

void del(char *host, char *username, int dataId) {
	
	CLIENT *clnt;
	int *result_1;
	struct SpecificId p = {dataId, username};
	//for (int i = 0; i < entry.noValues; i++)
	//	std::cout << p.data.value[i] << std::endl;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = delete_1(&p, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else if (*result_1 == OK) {
			std::cout << "Data deleted successfully" << std::endl;
	} else {
			std::cout << "Invalid id, the entry doesn't exist\n";
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	//return *result_1;
}

int update(char *host, char *username, struct SensorData entry) {
	CLIENT *clnt;
	int *result_1;
	struct UserPackage p = {entry, username};
	//for (int i = 0; i < entry.noValues; i++)
	//	std::cout << p.data.value[i] << std::endl;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB, RPC_DB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = update_1(&p, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		if (*result_1 == ERROR) {
			std::cout << "Error while updating data" << std::endl;
		} else {
			std::cout << "Update was successful" << std::endl;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

int main(int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	std::string command;
	bool keepRunning = true;
	int userKey = NOT_LOGGED_IN;
	int r;
	char username[LENGTH];
	std::string unauthorized_msg = "You need to be logged in to use this command.\n";
	std::string user_file;

	while (keepRunning) {
		std::cin >> command;

		if (command == "login") {
			if (userKey < 0) {
				std::cin >> username;
				userKey = login(host, username);
			} else {
				std::cout << "You are already logged in as: " << username << std::endl;
			}
		}

		else if (command == "add") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			int dataId;
			int noValues;
			float *values;
			std::cin >> dataId;
			std::cin >> noValues;
			struct SensorData entry;
			entry.dataId = dataId;
			entry.noValues = noValues;
			entry.value.value_len = noValues;
			entry.value.value_val = new float[noValues + 1];
			for (int i = 0; i < noValues; ++i) {
				std::cin >> entry.value.value_val[i];
			}
			add(host, username, entry);
		}

		else if (command == "read") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			int dataId;
			std::cin >> dataId;
			read(host, username, dataId);
		}

		else if (command == "getstat") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			int dataId;
			std::cin >> dataId;
			getstat(host, username, dataId);
		}

		else if (command == "readall") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			readall(host, username);
		}

		else if (command == "getstatall") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			getstatall(host, username);
		}

		else if (command == "del") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			int dataId;
			std::cin >> dataId;
			del(host, username, dataId);
		}		

		else if (command == "logout") {
			r = logout(host, username);
			if (r == SUCCESS || userKey < 0) {
				std::cout << "Logging user out\n";
				keepRunning = false;
			}
		}

		else if (command == "store") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			user_file = std::string(username) + ".rpcdb";
			std::cout << "Storing the following data:\n";
			std::string result = std::string(store(host, username));
			std::cout << result;
			std::ofstream outfile;
			outfile.open(user_file);
			outfile << result;
			outfile.close();
		}

		else if (command == "load") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			load(host, username);
		}

		else if (command == "update") {
			if (userKey < 0) {
				std::cout << unauthorized_msg;
				continue;
			}
			int dataId;
			int noValues;
			float *values;
			std::cin >> dataId;
			std::cin >> noValues;
			struct SensorData entry;
			entry.dataId = dataId;
			entry.noValues = noValues;
			entry.value.value_len = noValues;
			entry.value.value_val = new float[noValues + 1];
			for (int i = 0; i < noValues; ++i) {
				std::cin >> entry.value.value_val[i];
			}
			update(host, username, entry);			
		}

	}

	exit (0);
}