/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DB_H_RPCGEN
#define _RPC_DB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SensorData {
	int dataId;
	int noValues;
	struct {
		u_int value_len;
		float *value_val;
	} value;
};
typedef struct SensorData SensorData;

struct UserPackage {
	struct SensorData data;
	char *name;
};
typedef struct UserPackage UserPackage;

struct SpecificId {
	int dataId;
	char *name;
};
typedef struct SpecificId SpecificId;

#define RPC_DB 1
#define RPC_DB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(struct UserPackage *, CLIENT *);
extern  int * add_1_svc(struct UserPackage *, struct svc_req *);
#define DELETE 2
extern  int * delete_1(struct SpecificId *, CLIENT *);
extern  int * delete_1_svc(struct SpecificId *, struct svc_req *);
#define UPDATE 3
extern  int * update_1(struct UserPackage *, CLIENT *);
extern  int * update_1_svc(struct UserPackage *, struct svc_req *);
#define READ 4
extern  char ** read_1(struct SpecificId *, CLIENT *);
extern  char ** read_1_svc(struct SpecificId *, struct svc_req *);
#define GETSTAT 5
extern  char ** getstat_1(struct SpecificId *, CLIENT *);
extern  char ** getstat_1_svc(struct SpecificId *, struct svc_req *);
#define GETSTATALL 6
extern  char ** getstatall_1(char **, CLIENT *);
extern  char ** getstatall_1_svc(char **, struct svc_req *);
#define LOAD 7
extern  int * load_1(char **, CLIENT *);
extern  int * load_1_svc(char **, struct svc_req *);
#define STORE 8
extern  char ** store_1(char **, CLIENT *);
extern  char ** store_1_svc(char **, struct svc_req *);
#define LOGIN 9
extern  int * login_1(char **, CLIENT *);
extern  int * login_1_svc(char **, struct svc_req *);
#define LOGOUT 10
extern  int * logout_1(char **, CLIENT *);
extern  int * logout_1_svc(char **, struct svc_req *);
#define READALL 11
extern  char ** readall_1(char **, CLIENT *);
extern  char ** readall_1_svc(char **, struct svc_req *);
extern int rpc_db_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define DELETE 2
extern  int * delete_1();
extern  int * delete_1_svc();
#define UPDATE 3
extern  int * update_1();
extern  int * update_1_svc();
#define READ 4
extern  char ** read_1();
extern  char ** read_1_svc();
#define GETSTAT 5
extern  char ** getstat_1();
extern  char ** getstat_1_svc();
#define GETSTATALL 6
extern  char ** getstatall_1();
extern  char ** getstatall_1_svc();
#define LOAD 7
extern  int * load_1();
extern  int * load_1_svc();
#define STORE 8
extern  char ** store_1();
extern  char ** store_1_svc();
#define LOGIN 9
extern  int * login_1();
extern  int * login_1_svc();
#define LOGOUT 10
extern  int * logout_1();
extern  int * logout_1_svc();
#define READALL 11
extern  char ** readall_1();
extern  char ** readall_1_svc();
extern int rpc_db_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SensorData (XDR *, SensorData*);
extern  bool_t xdr_UserPackage (XDR *, UserPackage*);
extern  bool_t xdr_SpecificId (XDR *, SpecificId*);

#else /* K&R C */
extern bool_t xdr_SensorData ();
extern bool_t xdr_UserPackage ();
extern bool_t xdr_SpecificId ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DB_H_RPCGEN */
